---
- name: Deploy HTML Files
  hosts: "{{ target_host }}"
  become: true

  tasks:
    - name: Copy HTML File
      copy:
        src: "index-{{ target_host }}.html"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
